apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  labels:
    app: springboot-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8484
    protocol: TCP
  selector:
    app: springboot-app