apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-test
  labels:
    app: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8484"
    spec:
      containers:
      - name: springboot-app
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVER_PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service-test
  labels:
    app: springboot-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "80"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: springboot-app