name: Chain Deployment Pipeline

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      promote_to_staging:
        description: 'Promote to staging'
        required: true
        default: 'false'
        type: boolean
      promote_to_prod:
        description: 'Promote to production'
        required: true
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build JAR with Maven
      run: mvn clean install

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }} .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Dev
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}
          docker stop springboot-app || true
          docker rm springboot-app || true
          docker run -d -p 8484:8484 --name springboot-app ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}

  test-dev:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
    - name: Wait for deployment
      run: sleep 30

    - name: Test Dev Health
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_HOST }}:8484/hello)
        if [ $response -eq 200 ]; then
          echo "✅ Dev health check passed"
        else
          echo "❌ Dev health check failed"
          exit 1
        fi

  promote-to-staging:
    needs: test-dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Create Pull Request to Staging
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev-to-staging-${{ github.sha }}
        base: staging
        title: "🚀 Auto-promote dev to staging"
        body: |
          ## Dev → Staging Promotion
          
          ✅ Dev tests passed
          ✅ Health checks successful
          
          **Changes:**
          - SHA: ${{ github.sha }}
          - Branch: dev
          - Tested on: ${{ secrets.EC2_HOST }}:8484
          
          **Ready for staging deployment**
        labels: |
          auto-promotion
          staging-ready

  deploy-staging:
    needs: test-dev
    runs-on: ubuntu-latest
    if: github.event.inputs.promote_to_staging == 'true' || (github.ref == 'refs/heads/staging' && github.event_name == 'push')
    steps:
    - name: Deploy to Staging
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST_STAGING }}
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}
          docker stop springboot-app || true
          docker rm springboot-app || true
          docker run -d -p 8484:8484 --name springboot-app ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}

  test-staging:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.event.inputs.promote_to_staging == 'true' || (github.ref == 'refs/heads/staging' && github.event_name == 'push')
    steps:
    - name: Wait for deployment
      run: sleep 30

    - name: Test Staging Health
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_HOST_STAGING }}:8484/hello)
        if [ $response -eq 200 ]; then
          echo "✅ Staging health check passed"
        else
          echo "❌ Staging health check failed"
          exit 1
        fi

    - name: Test Staging Status Endpoint
      run: |
        response=$(curl -s http://${{ secrets.EC2_HOST_STAGING }}:8484/status)
        if [[ $response == *"Staging"* ]]; then
          echo "✅ Staging status check passed: $response"
        else
          echo "❌ Staging status check failed"
          exit 1
        fi

  promote-to-production:
    needs: test-staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Create Pull Request to Production
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: staging-to-prod-${{ github.sha }}
        base: main
        title: "🚀 Auto-promote staging to production"
        body: |
          ## Staging → Production Promotion
          
          ✅ Dev tests passed
          ✅ Staging tests passed
          ✅ Health checks successful
          
          **Changes:**
          - SHA: ${{ github.sha }}
          - Branch: staging
          - Tested on: ${{ secrets.EC2_HOST_STAGING }}:8484
          
          **Ready for production deployment**
        labels: |
          auto-promotion
          production-ready

  deploy-production:
    needs: promote-to-production
    runs-on: ubuntu-latest
    if: github.event.inputs.promote_to_prod == 'true'
    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST_PROD }}
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}
          docker stop springboot-app || true
          docker rm springboot-app || true
          docker run -d -p 8484:8484 --name springboot-app ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}

  notify-success:
    needs: [deploy-dev, test-dev, promote-to-staging]
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/dev'
    steps:
    - name: Dev Deployment Summary
      run: |
        echo "🎉 Dev Deployment Summary"
        echo "========================"
        echo "✅ Dev: http://${{ secrets.EC2_HOST }}:8484"
        echo "📝 Staging promotion PR created"
        echo "⏳ Awaiting staging approval"

  notify-staging-success:
    needs: [deploy-staging, test-staging, promote-to-production]
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/staging'
    steps:
    - name: Staging Deployment Summary
      run: |
        echo "🎉 Staging Deployment Summary"
        echo "============================"
        echo "✅ Staging: http://${{ secrets.EC2_HOST_STAGING }}:8484"
        echo "📝 Production promotion PR created"
        echo "⏳ Awaiting production approval"